package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type ArticleContent struct {
	ID                    primitive.ObjectID   `bson:"_id,omitempty" json:"_id,omitempty"`
	Title                 string               `bson:"title" json:"title" validate:"required"`
	Excerpt               string               `bson:"excerpt" json:"excerpt"`
	Content               string               `bson:"content" json:"content" validate:"required"`
	Image                 string               `bson:"image" json:"image"`                                   // URL or path to the generated image
	ArticleCategories     []primitive.ObjectID `bson:"article_categories" json:"article_categories"`         // References ArticleCategory
	RecommendedCategories []string             `bson:"recommended_categories" json:"recommended_categories"` // Generated by Gemini
	CreatedAt             time.Time            `bson:"created_at" json:"created_at"`
	UpdatedAt             time.Time            `bson:"updated_at" json:"updated_at"`
}
